apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gonsumidor-template
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: gonsumidor
    namespace: gontador
  spec:
    lookupPolicy:
      local: false


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: gonsumidor
    name: gonsumidor
    namespace: gontador
  spec:
    replicas: 2
    selector:
      app: gonsumidor
      deploymentconfig: gonsumidor
    template:
      metadata:
        labels:
          app: gonsumidor
          deploymentconfig: gonsumidor
      spec:
        containers:
          - image: >-
              172.30.1.1:5000/gonsumidor/gonsumidor@sha256:9fd64c947842884d6def85ca5ee907efefb2c636960ca5069a06eb89adeda1ec
            imagePullPolicy: Always
            name: gonsumidor
            # ports:
            #   - containerPort: 3000
            #     protocol: TCP
            
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
              - name: SERVER_ADDRESS
                value: '192.168.64.7:30001'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - gonsumidor
          from:
            kind: ImageStreamTag
            name: 'gonsumidor:latest'
            namespace: gontador
          # lastTriggeredImage: >-
          #   172.30.1.1:5000/gontador/gontador@sha256:9fd64c947842884d6def85ca5ee907efefb2c636960ca5069a06eb89adeda1ec
        type: ImageChange
      - type: ConfigChange
  status: {}
